#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Update package list and install HAProxy
sudo apt-get -y update
apt-get -y install haproxy

# Edit HAProxy configuration file
server_config=\
"
frontend http_front
        bind *:80
        mode http
        default_backend http_back
backend http_back
        balance roundrobin
        server 6928-web-01 3.87.214.45:80 check
        server 6928-web-02 54.164.129.143:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart