#!/usr/bin/env bash
# Honestly, I have now clue what this does, I just adapt to whatever ALU's intranet wants

# Check for correct number of arguments
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"

if [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP":~/
else
    PATH_TO_SSH_KEY="$4"
	scp -i $PATH_TO_SSH_KEY -o StrictHostKeyChecking=no $PATH_TO_FILE "$USERNAME@$IP":~/
fi